base_urls:
  default: "192.168.1.20"
  api: "https://192.168.1.100"
  device_control: "https://192.168.1.150"
  service_control: "https://192.168.1.200"
  xuanzheng: "192.168.1.20"
  robot_com: "192.168.23.10"

